apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awesome-app
  name: awesome-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awsome-app
  template:
    metadata:
      labels:
        app: awesomw-app
    spec:
      containers:
      - image: <container-registry>/awesome-app:v1
        name: awesome-app
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/os: linux
