apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awesome-app
  name: awesome-app-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awesome-app
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
      - image:  nginx
      # - image: ghcr.io/arogic/awesome-app:1.0.54
        name: awesome-app
        ports:
        # - containerPort: 8080
        - containerPort: 80
        imagePullPolicy: Always
      # imagePullSecrets:
      #   - name: argocd-pull-secret
      nodeSelector:
        kubernetes.io/os: linux
