apiVersion: v1
kind: Service
metadata:
  labels:
    app: awesome-app
  name: awesome-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: awesome-app
  type: LoadBalancer
