apiVersion: v1
kind: Service
metadata:
  name: {{ include "awesome-app.fullname" . }}
  # namespace: demo
  labels:
    {{- include "awesome-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "awesome-app.selectorLabels" . | nindent 4 }}
