# This is a basic workflow to help you get started with Actions

# Define a name of the workflow
name: Build and Publish Docker Image

# This controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: arogic/awesome-app:1.0
  # IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Show env
      #   run: |
      #     echo "GITHUB_RUN_NUMBER ${GITHUB_RUN_NUMBER}"
      #     env

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          # context: awesome-app
          # context: sample-app/azure-vote
          push: true
          # tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}.${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Bump Version
      #   run: |
      #     sed -i "s|1.0.[0-9]*|1.0.${GITHUB_RUN_NUMBER}|g" manifests/awesome-app.yml
      #     cat manifests/awesome-app.yml
      #     # git config --global user.email "bot@example.com"
      #     # git config --global user.name "git bot"
      #     # git add .
      #     # git commit -am 'bump version ${GITHUB_RUN_NUMBER}'
      #     # git push

      - name: Commit files
        run: |
          sed -i "s|1.0.[0-9]*|1.0.${GITHUB_RUN_NUMBER}|g" manifests/awesome-app.yml
          git config remote.origin.url https://github.com/arogic/awesome-app.git
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add -A
          git commit -am "bump version ${GITHUB_RUN_NUMBER}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
